name: test

on:
  pull_request_target:
    branches:
      - '**'

jobs:
  pack:
    name: test
    runs-on: 'ubuntu-22.04'
    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ github.event_name == 'pull_request_target' && format('refs/pull/{0}/merge', github.event.number) || '' }}
          persist-credentials: false
      - uses: ./.github/workflows/actions/test
