name: Workflow Run

on:
  workflow_run:
    workflows: ["Trigger"]
    types:
      - completed

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 1-${{ github.repository }}
          echo 2-${{ github.event.workflow_run.head_branch }}
          echo 3-${{ github.event.head_commit.id }}
          echo 4-${{ github.event.ref }}

